version: "2"

linters:
  default: standard
  enable:
    - modernize
    - gocritic
    - makezero
    - copyloopvar
    - nilerr
    - errorlint
    - testifylint
    - unparam
    - prealloc
    - nolintlint
    - usestdlibvars
    - misspell
  settings:
    gocritic:
      enabled-tags:
        - performance
        - style
    govet:
      enable-all: true

  exclusions:
    presets:
      - comments
    rules:      
      - path: .*_test\.go
        linters:
          - gocritic

formatters:
  enable:
    - gofmt

run:
  timeout: 5m
